---
pyenv_root: "{{ ansible_env.HOME }}/.pyenv"

pyenv_dependencies:
  - make
  - build-essential
  - libssl-dev
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - wget
  - curl
  - llvm
  - libncursesw5-dev
  - xz-utils
  - tk-dev
  - libxml2-dev
  - libxmlsec1-dev
  - libffi-dev
  - liblzma-dev
  - git

python_versions:
  - "3.10.13"
  - "3.11.6"
  - "3.12.3"

global_python_version: "3.11.6"

virtualenvs:
  - { name: "env310",         version: "3.10.13" }
  - { name: "env311",         version: "3.11.6" }
  - { name: "blog_writer",    version: "3.11.6" }
  - { name: "shortcutwidget", version: "3.12.3" }
